# Generated by Django 3.2.8 on 2024-04-06 04:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240406_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='images',
        ),
        migrations.AddField(
            model_name='page',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(default=1, upload_to='page_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
