# Generated by Django 3.2.8 on 2024-04-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20240406_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='created',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=1, upload_to='post_images/'),
            preserve_default=False,
        ),
    ]
